from __future__ import annotations

import os


NAME = "Manual Actions"
VERSION = "1.6.2"
DESCRIPTION = (
	"Ручное управление заказами прямо из Telegram + встроенный Chat Sync.\n\n"
	"Chat Sync зеркалит FunPay чаты в темы Telegram-форума и работает на одном боте - самом Cardinal.\n\n"
	"Работает в двух режимах:\n"
	"• В теме Chat Sync - команды без аргументов, контекст берётся из темы автоматически.\n"
	"• В любом чате - команды с явными аргументами.\n\n"
	"/setup_sync_chat - привязать группу-форум\n"
	"/sync_chats - создать темы для всех чатов\n"
	"/history, /full_history - история чата в теме\n"
	"/watch - что смотрит собеседник\n"
	"/refund [ID] - сделать возврат\n"
	"/bl [ник] - переключить чёрный список\n"
"/bl_list - показать чёрный список\n"
"/lot [ID] - показать информацию о лоте\n"
"/lots on/off - включить или выключить все лоты\n"
"/orders [ник] - показать заказы пользователя\n"
	"/profit - посчитать прибыль за период\n"
	"/actions - открыть меню Manual Actions\n"
	"/gist <текст> - создать GitHub Gist\n"
	"/templates - отправить заготовку в теме Chat Sync\n"
	"/status [0/1/2] - переключить текущий статус\n"
	"!code [ID] - показать код 2FA для заказа\n"
	"!status - показать статус в FunPay"
)
CREDITS = "beavers_best"
UUID = "b7e2d3f4-1a2b-4c5d-8e9f-0a1b2c3d4e5f"
SETTINGS_PAGE = True

LOGGER_NAME = "FPC.manual_actions"
LOGGER_PREFIX = "[MANUAL]"

PLUGIN_FOLDER = "storage/plugins/manual_actions"
SETTINGS_FILE = os.path.join(PLUGIN_FOLDER, "settings.json")
GEMINI_DELIVERY_FILE = os.path.join(PLUGIN_FOLDER, "gemini_delivery.json")
GPT_ACCOUNTS_DELIVERY_FILE = os.path.join(PLUGIN_FOLDER, "gpt_accounts_delivery.json")
TWO_FACTOR_FILE = os.path.join(PLUGIN_FOLDER, "two_factor.json")
CHAT_SYNC_TOPICS_FILE = os.path.join(PLUGIN_FOLDER, "chat_sync_topics.json")

SYNC_PLUGIN_UUID = "745ed27e-3196-47c3-9483-e382c09fd2d8"

CBT_BL_UNBL = "ma_unbl:"
CBT_BL_LIST = "ma_bl_list:"
CBT_BL_CONFIRM = "ma_bl_confirm:"
CBT_BL_CANCEL = "ma_bl_cancel:"
CBT_BL_USER = "ma_bl_user:"
CBT_BL_UNBLOCK = "ma_bl_unblock:"
CBT_BLACKLIST_PAGE = "ma_blacklist_page:"
CBT_REFUND_CNF = "ma_rfcnf:"
CBT_REFUND_CANCEL = "ma_rfcancel:"

CBT_LOT_REFRESH = "ma_lot_refresh:"
CBT_LOT_VIEWED = "ma_lot_viewed:"
CBT_LOT_SECTION = "ma_lot_section:"
CBT_LOTS_PAGE = "ma_lots_page:"
CBT_LOTS_REQUEST = "ma_lots_request:"
CBT_LOTS_CONFIRM = "ma_lots_confirm:"
CBT_LOTS_CANCEL = "ma_lots_cancel:"

CBT_ORDERS_PAGE = "ma_orders_page:"
CBT_ORDERS_FILTER = "ma_orders_filter:"
CBT_ORDERS_DETAIL = "ma_orders_detail:"
CBT_ORDERS_REFUND = "ma_orders_refund:"

CBT_PROFIT_PAGE = "ma_profit_page:"
CBT_PROFIT_PERIOD = "ma_profit_period:"
CBT_PROFIT_CUSTOM = "ma_profit_custom:"
CBT_PROFIT_TOGGLE_PAID = "ma_profit_toggle_paid:"

CBT_WITHDRAWAL_PAGE = "ma_withdrawal_page:"
CBT_WITHDRAWAL_METHOD = "ma_withdrawal_method:"

CBT_STATUS_PAGE = "ma_status_page:"
CBT_STATUS_CATEGORY = "ma_status_category:"
CBT_STATUS_DETAIL = "ma_status_detail:"
CBT_STATUS_SET = "ma_status_set:"
CBT_STATUS_EDIT_RESPONSE = "ma_status_edit_response:"
CBT_STATUS_EDIT_AUTO = "ma_status_edit_auto:"
CBT_STATUS_TOGGLE_AUTO = "ma_status_toggle_auto:"

CBT_TEMPLATES_PAGE = "ma_templates_page:"
CBT_TEMPLATES_CATEGORY = "ma_templates_category:"
CBT_TEMPLATE_DETAIL = "ma_template_detail:"
CBT_TEMPLATE_ADD = "ma_template_add:"
CBT_TEMPLATE_EDIT_TITLE = "ma_template_edit_title:"
CBT_TEMPLATE_EDIT_TEXT = "ma_template_edit_text:"
CBT_TEMPLATE_DELETE = "ma_template_delete:"
CBT_TEMPLATE_DELETE_CONFIRM = "ma_template_delete_confirm:"
CBT_TEMPLATE_DELETE_CANCEL = "ma_template_delete_cancel:"
CBT_TEMPLATES_SELECT = "ma_templates_select:"
CBT_TEMPLATES_SEND = "ma_templates_send:"
CBT_TEMPLATES_CANCEL = "ma_templates_cancel:"

CBT_GIST_PAGE = "ma_gist_page:"
CBT_GIST_CATEGORY = "ma_gist_category:"
CBT_GIST_TOKEN_PAGE = "ma_gist_token_page:"
CBT_GIST_FILENAME_PAGE = "ma_gist_filename_page:"
CBT_GIST_VISIBILITY_PAGE = "ma_gist_visibility_page:"
CBT_GIST_SET_FILENAME_MODE = "ma_gist_set_filename_mode:"
CBT_GIST_SET_VISIBILITY = "ma_gist_set_visibility:"
CBT_GIST_EDIT_TOKEN = "ma_gist_edit_token:"
CBT_GIST_EDIT_CUSTOM_FILENAME = "ma_gist_edit_filename:"
CBT_GIST_ORDER_SELECT = "ma_gist_order_select:"
CBT_GIST_ORDER_CANCEL = "ma_gist_order_cancel:"
CBT_GIST_SEND = "ma_gist_send:"
CBT_GIST_SKIP_SEND = "ma_gist_skip_send:"

CBT_GEMINI_PAGE = "ma_gemini:"
CBT_GEMINI_CATEGORY = "ma_gemini_category:"
CBT_GEMINI_TOGGLE = "ma_gemini_toggle:"
CBT_GEMINI_ADD = "ma_gemini_add:"
CBT_GEMINI_STOCK = "ma_gemini_stock:"
CBT_GEMINI_LINK = "ma_gemini_link:"
CBT_GEMINI_DELETE = "ma_gemini_delete:"
CBT_GEMINI_DELETE_CONFIRM = "ma_gemini_delete_confirm:"
CBT_GEMINI_DELETE_CANCEL = "ma_gemini_delete_cancel:"
CBT_GEMINI_CLEAR = "ma_gemini_clear:"
CBT_GEMINI_CLEAR_CONFIRM = "ma_gemini_clear_confirm:"
CBT_GEMINI_SHORTAGE = "ma_gemini_shortage:"
CBT_GEMINI_SET_SHORTAGE = "ma_gemini_set_shortage:"
CBT_GEMINI_EDIT_TEMPLATE = "ma_gemini_edit_template:"
CBT_GEMINI_EDIT_DELAY = "ma_gemini_edit_delay:"
CBT_GEMINI_WAITING = "ma_gemini_waiting:"
CBT_GEMINI_RETRY = "ma_gemini_retry:"

CBT_AUTO_DELIVERY_PAGE = "ma_auto_delivery:"
CBT_GPT_ACCOUNTS_PAGE = "ma_gpt_accounts:"
CBT_GPT_ACCOUNTS_CATEGORY = "ma_gpt_accounts_category:"
CBT_GPT_ACCOUNTS_TOGGLE = "ma_gpt_accounts_toggle:"
CBT_GPT_ACCOUNTS_ADD = "ma_gpt_accounts_add:"
CBT_GPT_ACCOUNTS_STOCK = "ma_gpt_accounts_stock:"
CBT_GPT_ACCOUNTS_ACCOUNT = "ma_gpt_accounts_account:"
CBT_GPT_ACCOUNTS_DELETE = "ma_gpt_accounts_delete:"
CBT_GPT_ACCOUNTS_DELETE_CONFIRM = "ma_gpt_accounts_delete_confirm:"
CBT_GPT_ACCOUNTS_CLEAR = "ma_gpt_accounts_clear:"
CBT_GPT_ACCOUNTS_CLEAR_CONFIRM = "ma_gpt_accounts_clear_confirm:"
CBT_GPT_ACCOUNTS_SHORTAGE = "ma_gpt_accounts_shortage:"
CBT_GPT_ACCOUNTS_SET_SHORTAGE = "ma_gpt_accounts_set_shortage:"
CBT_GPT_ACCOUNTS_EDIT_TEMPLATE = "ma_gpt_accounts_edit_template:"
CBT_GPT_ACCOUNTS_EDIT_DELAY = "ma_gpt_accounts_edit_delay:"
CBT_GPT_ACCOUNTS_WAITING = "ma_gpt_accounts_waiting:"
CBT_GPT_ACCOUNTS_RETRY = "ma_gpt_accounts_retry:"

CBT_UPDATER_PAGE = "ma_updater_page:"
CBT_UPDATER_CATEGORY = "ma_updater_category:"
CBT_UPDATER_CHECK = "ma_updater_check:"
CBT_UPDATER_MODE_PAGE = "ma_updater_mode_page:"
CBT_UPDATER_INTERVAL_PAGE = "ma_updater_interval_page:"
CBT_UPDATER_MODE = "ma_updater_mode:"
CBT_UPDATER_INTERVAL = "ma_updater_interval:"
CBT_UPDATER_CUSTOM_INTERVAL = "ma_updater_custom_interval:"
CBT_UPDATER_INSTALL = "ma_updater_install:"
CBT_UPDATER_SKIP = "ma_updater_skip:"

CBT_CHAT_SYNC_PAGE = "ma_chat_sync_page:"
CBT_CHAT_SYNC_CATEGORY = "ma_chat_sync_category:"
CBT_CHAT_SYNC_TOGGLE = "ma_chat_sync_toggle:"
CBT_CHAT_SYNC_SYNC = "ma_chat_sync_sync:"
CBT_CHAT_SYNC_UNBIND = "ma_chat_sync_unbind:"
CBT_CHAT_SYNC_UNBIND_CONFIRM = "ma_chat_sync_unbind_confirm:"
CBT_CHAT_SYNC_EDIT_DEPTH = "ma_chat_sync_edit_depth:"
CBT_CHAT_SYNC_EDIT_RATE = "ma_chat_sync_edit_rate:"
CBT_CHAT_SYNC_IMPORT = "ma_chat_sync_import:"
CBT_CHAT_SYNC_IMPORT_CONFIRM = "ma_chat_sync_import_confirm:"
CBT_CHAT_SYNC_IMPORT_SKIP = "ma_chat_sync_import_skip:"

CBT_TWO_FACTOR_PAGE = "ma_two_factor_page:"
CBT_TWO_FACTOR_EDIT_LABEL = "ma_two_factor_edit_label:"

STATE_STATUS_RESPONSE = "ma_status_response_text"
STATE_STATUS_AUTO = "ma_status_auto_text"
STATE_TEMPLATE_CREATE_TITLE = "ma_template_create_title"
STATE_TEMPLATE_CREATE_TEXT = "ma_template_create_text"
STATE_TEMPLATE_EDIT_TITLE = "ma_template_edit_title"
STATE_TEMPLATE_EDIT_TEXT = "ma_template_edit_text"
STATE_UPDATER_CUSTOM_INTERVAL = "ma_updater_custom_interval"
STATE_GIST_TOKEN = "ma_gist_token"
STATE_GIST_CUSTOM_FILENAME = "ma_gist_custom_filename"
STATE_GEMINI_ADD = "ma_gemini_add"
STATE_GEMINI_TEMPLATE = "ma_gemini_template"
STATE_GEMINI_DELAY = "ma_gemini_delay"
STATE_GPT_ACCOUNTS_ADD = "ma_gpt_accounts_add"
STATE_GPT_ACCOUNTS_TEMPLATE = "ma_gpt_accounts_template"
STATE_GPT_ACCOUNTS_DELAY = "ma_gpt_accounts_delay"
STATE_TWO_FACTOR_LABEL = "ma_two_factor_label"
STATE_PROFIT_CUSTOM_PERIOD = "ma_profit_custom_period"
STATE_CHAT_SYNC_DEPTH = "ma_chat_sync_depth"
STATE_CHAT_SYNC_RATE = "ma_chat_sync_rate"
